### ISSUE TITLE
Typo in basic javascript examples

### ISSUE THREAD

**Issue by kounelios13** [devstaff-crete/meetup02-NodeJS#7]
In[ basic javascript examples](https://github.com/devstaff-crete/meetup02-NodeJS/blob/master/nodejs-tutorial.md) there is a serious typo.
Specifically in this line:
`var myObj = {name: Nikos, age: 33 }`
As it is written `Nikos` refers to a variable .I think it should be a string like this

`var myObj = {name: "Nikos", age: 33 }`

**Comment by gsaslis** [comment]
fixed by #8
